apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: jovisimons/dekeet-apigateway:latest
          name: api-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8095
          env:
            - name: AUTH_URL
              value: "http://auth-service:8092"
            - name: USER_URL
              value: "http://user-service:8094"
          resources:
            requests:
              memory: 100Mi
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "500m"